import { Routes } from '@angular/router';
import { BarcoListaComponent } from './barco/barco-lista/barco-lista.component';
import { BarcoViewComponent } from './barco/barco-view/barco-view.component';
import { BarcoEditComponent } from './barco/barco-edit/barco-edit.component';
import { BarcoCreateComponent } from './barco/barco-create/barco-create.component';
import { JugadorListaComponent } from './jugador/jugador-lista/jugador-lista.component';
import { JugadorViewComponent } from './jugador/jugador-view/jugador-view.component';
import { JugadorEditComponent } from './jugador/jugador-edit/jugador-edit.component';
import { JugadorCreateComponent } from './jugador/jugador-create/jugador-create.component';
import { MapaListaComponent } from './mapa/mapa-lista/mapa-lista.component';
import { MapaCreateComponent } from './mapa/mapa-create/mapa-create.component';
import { MapaViewComponent } from './mapa/mapa-view/mapa-view.component';
import { PartidaMenuComponent } from './partida/partida-menu/partida-menu.component';
import { PartidaCrearComponent } from './partida/partida-crear/partida-crear.component';
import { HomeComponent } from './home/home.component';

export const routes: Routes = [
    { path: '', component: HomeComponent },
    { path: 'barco/list', component: BarcoListaComponent },
    { path: 'barco/create', component: BarcoCreateComponent },
    { path: 'barco/view/:id', component: BarcoViewComponent },
    { path: 'barco/edit/:id', component: BarcoEditComponent },
    { path: 'jugador/list', component: JugadorListaComponent },
    { path: 'jugador/create', component: JugadorCreateComponent },
    { path: 'jugador/view/:id', component: JugadorViewComponent },
    { path: 'jugador/edit/:id', component: JugadorEditComponent },
    { path: 'mapa/list', component: MapaListaComponent },
    { path: 'mapa/create', component: MapaCreateComponent },
    { path: 'mapa/view/:id', component: MapaViewComponent },
    { path: 'partida/menu', component: PartidaMenuComponent },
    { path: 'partida/crear', component: PartidaCrearComponent }
];
