import { Routes } from '@angular/router';
import { BarcoListaComponent } from './barco/barco-lista/barco-lista.component';
import { BarcoViewComponent } from './barco/barco-view/barco-view.component';
import { BarcoEditComponent } from './barco/barco-edit/barco-edit.component';
import { BarcoCreateComponent } from './barco/barco-create/barco-create.component';
import { JugadorListaComponent } from './jugador/jugador-lista/jugador-lista.component';
import { JugadorViewComponent } from './jugador/jugador-view/jugador-view.component';
import { JugadorEditComponent } from './jugador/jugador-edit/jugador-edit.component';
import { JugadorCreateComponent } from './jugador/jugador-create/jugador-create.component';
import { HomeComponent } from './home/home.component';
import { ModeloListaComponent } from './modelo/modelo-lista/modelo-lista.component';
import { ModeloViewComponent } from './modelo/modelo-view/modelo-view.component';
import { ModeloEditComponent } from './modelo/modelo-edit/modelo-edit.component';
import { ModeloCreateComponent } from './modelo/modelo-create/modelo-create.component';

export const routes: Routes = [
    { path: '', component: HomeComponent },
    { path: 'barco/list', component: BarcoListaComponent },
    { path: 'barco/create', component: BarcoCreateComponent },
    { path: 'barco/view/:id', component: BarcoViewComponent },
    { path: 'barco/edit/:id', component: BarcoEditComponent },
    { path: 'jugador/list', component: JugadorListaComponent },
    { path: 'jugador/create', component: JugadorCreateComponent },
    { path: 'jugador/view/:id', component: JugadorViewComponent },
    { path: 'jugador/edit/:id', component: JugadorEditComponent },
    { path: 'modelo/list', component: ModeloListaComponent },
    { path: 'modelo/create', component: ModeloCreateComponent },
    { path: 'modelo/view/:id', component: ModeloViewComponent },
    { path: 'modelo/edit/:id', component: ModeloEditComponent }
];
